# Generated by Django 3.1.2 on 2020-12-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internfair', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='intern_count',
            field=models.IntegerField(default=0),
        ),
    ]
