# Generated by Django 3.1.2 on 2020-11-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internfair', '0002_auto_20201113_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='startups',
            name='companyName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='students',
            name='department',
            field=models.CharField(default='', max_length=50),
        ),
    ]
