# Generated by Django 3.1.2 on 2020-11-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internfair', '0004_auto_20201113_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='startups',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='startups',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
