# Generated by Django 3.1.2 on 2020-11-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internfair', '0005_auto_20201130_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startups',
            name='description',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='startups',
            name='location',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
