# Generated by Django 3.1.2 on 2020-12-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internfair', '0006_auto_20201130_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='bio',
            field=models.CharField(default='', max_length=100),
        ),
    ]
