# Generated by Django 3.1.2 on 2020-12-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internfair', '0007_students_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startups',
            name='description',
            field=models.CharField(default='Edit Profile to add description', max_length=500),
        ),
        migrations.AlterField(
            model_name='startups',
            name='location',
            field=models.CharField(default='Edit profile to add location', max_length=100),
        ),
        migrations.AlterField(
            model_name='students',
            name='bio',
            field=models.CharField(default='Edit Profile to add bio', max_length=500),
        ),
    ]
