# Generated by Django 3.1.2 on 2020-12-05 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internfair', '0002_auto_20201205_2327'),
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[(0, 'REJECTED'), (2, 'SHORTLISTED'), (1, 'PENDING')], default='PENDING', max_length=20)),
                ('Answers', models.TextField(max_length=200)),
                ('Intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internfair.students')),
                ('Internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.intern_form')),
            ],
        ),
    ]
