# Generated by Django 3.1.2 on 2020-12-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internapplication',
            name='Status',
            field=models.CharField(choices=[('SHORTLISTED', 'shortlisted'), ('REJECTED', 'rejected'), ('PENDING', 'pending')], default='PENDING', max_length=20),
        ),
    ]
