# Generated by Django 3.1.2 on 2020-12-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internapplication',
            name='Status',
            field=models.CharField(choices=[(2, 'SHORTLISTED'), (1, 'PENDING'), (0, 'REJECTED')], default=1, max_length=20),
        ),
    ]
