# Generated by Django 3.1.2 on 2020-12-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_auto_20201207_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internapplication',
            name='Status',
            field=models.CharField(choices=[('SHORTLISTED', 'shortlisted'), ('PENDING', 'pending'), ('REJECTED', 'rejected')], default=1, max_length=20),
        ),
    ]
