# Generated by Django 3.1.2 on 2020-12-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0003_auto_20201207_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internapplication',
            name='Status',
            field=models.CharField(choices=[('REJECTED', 'rejected'), ('SHORTLISTED', 'shortlisted'), ('PENDING', 'pending')], default='PENDING', max_length=20),
        ),
    ]
