# Generated by Django 3.1.2 on 2020-12-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0004_auto_20201208_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern_form',
            name='FormStatus',
            field=models.CharField(choices=[('DEACTIVE', 'DEACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='internapplication',
            name='Status',
            field=models.CharField(choices=[('SHORTLISTED', 'shortlisted'), ('REJECTED', 'rejected'), ('PENDING', 'pending')], default='PENDING', max_length=20),
        ),
    ]
