# Generated by Django 3.1.2 on 2020-12-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0007_auto_20201208_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern_form',
            name='remarks',
            field=models.CharField(default='.', max_length=200),
        ),
        migrations.AddField(
            model_name='internapplication',
            name='CV',
            field=models.CharField(default='not submitted', max_length=200),
        ),
        migrations.AlterField(
            model_name='intern_form',
            name='FormStatus',
            field=models.CharField(choices=[('DEACTIVE', 'DEACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='internapplication',
            name='Answers',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='internapplication',
            name='Status',
            field=models.CharField(choices=[('SHORTLISTED', 'shortlisted'), ('PENDING', 'pending'), ('REJECTED', 'rejected')], default='PENDING', max_length=20),
        ),
    ]
