# Generated by Django 3.1.2 on 2020-12-10 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_auto_20201207_1339'),
        ('recruiter', '0008_auto_20201210_1205'),
    ]

    operations = [
    ]
