# Generated by Django 3.1.2 on 2020-12-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0009_merge_20201210_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internapplication',
            name='CV',
            field=models.CharField(default='not submitted', max_length=500),
        ),
        migrations.AlterField(
            model_name='internapplication',
            name='Status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('REJECTED', 'rejected'), ('SHORTLISTED', 'shortlisted')], default='PENDING', max_length=20),
        ),
    ]
