# Generated by Django 3.1.2 on 2020-12-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0010_auto_20201210_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern_form',
            name='FormStatus',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DEACTIVE', 'DEACTIVE')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='internapplication',
            name='Status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('SHORTLISTED', 'shortlisted'), ('REJECTED', 'rejected')], default='PENDING', max_length=20),
        ),
    ]
